baseURL = 'https://bonschorno.org/'
languageCode = 'en-us'
title = "C.W."
theme = "typo"

[params]
homeIntroTitle = "Salut! ðŸ‘‹"

homeIntroContent = """
"""

# Main menu pages

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "vinyls"
url = "/vinyls"

[[params.menu]]
name = "pizza"
url = "/pizza"

[[params.menu]]
name = "about"
url = "/about"

footerContent = "Powered by [Hugo](https://gohugo.io/), co-created with [Claude](https://claude.ai/), and theme based on [tomfran/typo](https://github.com/tomfran/typo)"