baseURL = 'https://bonschorno.org/'
languageCode = 'en-us'
title = "C.W."
theme = "typo"

[params]
homeIntroTitle = "Salut! ðŸ‘‹"

homeIntroContent = """
"""

# Main menu pages

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "vinyls"
url = "/vinyls"

[[params.menu]]
name = "pizza"
url = "/pizza"

[[params.menu]]
name = "about"
url = "/about"

[[params.social]]
name = "github"
url = "https://github.com/bonschorno"